name: Terraform CI Dev

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/**'
  workflow_dispatch:

env:
  TF_ENV: "dev"
  TF_VERSION: "1.8.5"

jobs:
  terraform-format:
    name: 'terraform format'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2